## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.3
  - 1.4
  - nightly
env:
  matrix:
    - FORCE_COMPILE_NLOPT=yes
    - FORCE_COMPILE_NLOPT=no
notifications:
  email: false
