language: julia
os:
    - linux
    - osx
julia:
    - 0.4
    - 0.5
    - 0.6
    - nightly
addons:
    apt: # apt-get for linux
        packages:
            - libnlopt0 # We install it this way to be able to run Travis with `sudo: false`
notifications:
    email: false
sudo: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("NLopt")'
    - julia -e 'Pkg.test("NLopt", coverage=true)'
