language: julia
os:
    - linux
    - osx
julia:
    - 0.7
    - nightly
env:
  matrix:
    - FORCE_COMPILE_NLOPT=yes
    - FORCE_COMPILE_NLOPT=no
notifications:
    email: false
sudo: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("NLopt")'
    - julia -e 'Pkg.test("NLopt", coverage=true)'
